"""Write topol_cg.top: the MARTINI 3 system flattened into one moleculetype.

bakery reads a single CG moleculetype (the published multi-component systems
used flattened CG topologies as well), so the 128 POPC and 1752 W of
cg_conf.gro are written as one molecule, in that order. The [ atomtypes ] of
the used bead types are written inline for bakery; the #include keeps the full
MARTINI [ nonbond_params ] for backmap-prep's CG pair tables.

    uv run python make_cg_topology.py   (after fetch_sources.sh)
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from backmap_prep.parsers import parse_top

HERE = Path(__file__).resolve().parent
COUNTS = [("POPC", 128), ("W", 1752)]
MARTINI = [
    "martini_v3.0.0.itp",
    "martini_v3.0.0_phospholipids_v1.itp",
    "martini_v3.0.0_solvents_v1.itp",
]


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        probe = Path(tmp) / "probe.top"
        probe.write_text("".join(f'#include "{HERE / f}"\n' for f in MARTINI))
        top = parse_top(probe, include_dirs=[HERE])
    atoms, bonds, angles = [], [], []
    types: dict[str, float] = {}
    offset = resnr = 0
    for name, count in COUNTS:
        mol = top.molecule_types[name]
        for _ in range(count):
            resnr += 1
            for a in mol.atoms:
                types[a.type] = top.atom_types[a.type].mass
                atoms.append(
                    f"{a.index + offset:6d} {a.type:5s} {resnr:5d} {name:5s} {a.name:5s} "
                    f"{a.index + offset:6d} {a.charge:6.2f}"
                )
            bonds += [
                f"{b.i + offset:6d} {b.j + offset:6d} {b.func} "
                + " ".join(f"{p:g}" for p in b.params)
                for b in mol.bonds
            ]
            angles += [
                f"{t.i + offset:6d} {t.j + offset:6d} {t.k + offset:6d} {t.func} "
                + " ".join(f"{p:g}" for p in t.params)
                for t in mol.angles
            ]
            offset += len(mol.atoms)
    lines = [
        "; MARTINI 3.0.0 POPC bilayer in W, flattened into one moleculetype.",
        "; Generated by make_cg_topology.py from the pinned MARTINI files.",
        '#include "martini_v3.0.0.itp"',
        "",
        "[ atomtypes ]",
        *(f"{t:5s} {m:8.3f} 0.000 A 0.0 0.0" for t, m in sorted(types.items())),
        "",
        "[ moleculetype ]",
        "SYS 1",
        "",
        "[ atoms ]",
        *atoms,
        "",
        "[ bonds ]",
        *bonds,
        "",
        "[ angles ]",
        *angles,
        "",
        "[ system ]",
        "MARTINI 3 POPC bilayer (insane), 1 us NPT at 310 K",
        "",
        "[ molecules ]",
        "SYS 1",
        "",
    ]
    (HERE / "topol_cg.top").write_text("\n".join(lines))
    print(f"{offset} atoms, {len(bonds)} bonds, {len(angles)} angles, types {sorted(types)}")


if __name__ == "__main__":
    main()
