"""LAMMPS data file and input script writers."""

from __future__ import annotations

from typing import TYPE_CHECKING

from . import units

if TYPE_CHECKING:
    from pathlib import Path

    from .builder import System
    from .schema import Settings


def write_lammps_data(system: System, path: Path) -> None:
    """Write a LAMMPS data file (atom_style full)."""
    with open(path, "w") as f:
        f.write("LAMMPS data file for backmapping — generated by backmap-prep\n\n")

        f.write(f"{len(system.atoms)} atoms\n")
        f.write(f"{len(system.bonds)} bonds\n")
        f.write(f"{len(system.angles)} angles\n")
        f.write("0 dihedrals\n")
        f.write("0 impropers\n\n")

        f.write(f"{len(system.atom_types)} atom types\n")
        f.write(f"{len(system.bond_types)} bond types\n")
        f.write(f"{len(system.angle_types)} angle types\n")
        f.write("0 dihedral types\n")
        f.write("0 improper types\n\n")

        bx, by, bz = system.box
        f.write(f"0.0 {bx:.6f} xlo xhi\n")
        f.write(f"0.0 {by:.6f} ylo yhi\n")
        f.write(f"0.0 {bz:.6f} zlo zhi\n\n")

        # Masses
        f.write("Masses\n\n")
        for at in system.atom_types:
            label = f"# {at.name}" + (" (CG)" if at.is_cg else "")
            f.write(f"{at.type_id} {at.mass:.6f} {label}\n")
        f.write("\n")

        # Atoms
        f.write("Atoms # full\n\n")
        for a in system.atoms:
            f.write(
                f"{a.atom_id} {a.mol_id} {a.type_id} {a.charge:.6f} {a.x:.6f} {a.y:.6f} {a.z:.6f}\n"
            )
        f.write("\n")

        # Bonds
        if system.bonds:
            f.write("Bonds\n\n")
            for b in system.bonds:
                f.write(f"{b.bond_id} {b.type_id} {b.i} {b.j}\n")
            f.write("\n")

        # Angles
        if system.angles:
            f.write("Angles\n\n")
            for ang in system.angles:
                f.write(f"{ang.angle_id} {ang.type_id} {ang.i} {ang.j} {ang.k}\n")
            f.write("\n")

    # Print type mapping tables
    print("\n--- Atom type mapping ---")
    for atype in system.atom_types:
        kind = "CG" if atype.is_cg else "AT"
        print(f"  Type {atype.type_id} = {atype.name} ({kind})")

    print("\n--- Bond type mapping ---")
    for bt in system.bond_types:
        kw = f" {bt.keyword}" if bt.keyword else ""
        extra = f" (table: {bt.table_file})" if bt.table_file else ""
        print(f"  Bond type {bt.type_id} = {bt.style}{kw}{extra}")

    if system.angle_types:
        print("\n--- Angle type mapping ---")
        for angtype in system.angle_types:
            kw = f" {angtype.keyword}" if angtype.keyword else ""
            print(f"  Angle type {angtype.type_id} = {angtype.style}{kw}")


def write_lammps_input(
    system: System,
    settings: Settings,
    path: Path,
    data_filename: str,
) -> None:
    """Write a LAMMPS input script for backmapping."""
    sim = settings.simulation

    # Convert units
    timestep_fs = units.time(sim.timestep)
    lj_cut_ang = units.distance(sim.lj_cutoff)
    cg_cut_ang = units.distance(sim.cg_cutoff)
    coul_cut_ang = units.distance(sim.coulomb_cutoff)
    gamma_inv_fs = units.time(1.0 / sim.thermostat_gamma) if sim.thermostat_gamma > 0 else 100.0
    backmapping_steps = int(1.0 / sim.alpha)

    # Collect unique CG types for table pair coeffs
    cg_type_ids = sorted({at.type_id for at in system.atom_types if at.is_cg})
    at_type_ids = sorted({at.type_id for at in system.atom_types if not at.is_cg})

    # Determine bond/angle style lines
    has_static_bonds = any(bt.style == "harmonic" for bt in system.bond_types)
    has_backmap_harm = any(bt.style == "backmap/harmonic" for bt in system.bond_types)
    has_backmap_table = any(bt.style == "backmap/table" for bt in system.bond_types)

    bond_styles = []
    if has_static_bonds:
        bond_styles.append("harmonic")
    if has_backmap_harm:
        bond_styles.append("backmap/harmonic")
    if has_backmap_table:
        bond_styles.append("backmap/table linear 1000")

    has_static_angles = any(at.style == "harmonic" for at in system.angle_types)
    has_backmap_angles = any(at.style == "backmap/harmonic" for at in system.angle_types)

    angle_styles = []
    if has_static_angles:
        angle_styles.append("harmonic")
    if has_backmap_angles:
        angle_styles.append("backmap/harmonic")

    with open(path, "w") as f:
        f.write("# LAMMPS input for backmapping — generated by backmap-prep\n")
        f.write("# Reference: Krajniak et al., JCTC 2016, DOI: 10.1021/acs.jctc.6b00595\n")
        f.write("#            Krajniak, Zhang et al., JCC 2018, DOI: 10.1002/jcc.25129\n\n")

        f.write("units real\n")
        f.write("atom_style full\n")
        f.write("boundary p p p\n\n")

        f.write(f"read_data {data_filename}\n\n")

        # Pair style
        f.write(
            f"pair_style backmap {lj_cut_ang:.2f} lj/cut/coul/cut {lj_cut_ang:.2f} {coul_cut_ang:.2f} "
            f"{cg_cut_ang:.2f} table linear 1000\n"
        )
        for pt in system.pair_types:
            if pt.kind == "atomistic":
                f.write(
                    f"pair_coeff {pt.itype} {pt.jtype} atomistic {pt.epsilon:.6f} {pt.sigma:.6f}\n"
                )
            elif pt.kind == "cg":
                if pt.table_file:
                    f.write(
                        f"pair_coeff {pt.itype} {pt.jtype} cg {pt.table_file} {pt.table_keyword}\n"
                    )
                else:
                    f.write(f"pair_coeff {pt.itype} {pt.jtype} cg 0.0 0.0\n")
            else:
                f.write(f"pair_coeff {pt.itype} {pt.jtype} none\n")
        f.write("\n")

        # Bond style
        if len(bond_styles) > 1:
            f.write(f"bond_style hybrid {' '.join(bond_styles)}\n")
        elif bond_styles:
            f.write(f"bond_style {bond_styles[0]}\n")

        for bt in system.bond_types:
            if len(bond_styles) > 1:
                if bt.style == "harmonic":
                    f.write(
                        f"bond_coeff {bt.type_id} harmonic {bt.params[0]:.6f} {bt.params[1]:.6f}\n"
                    )
                elif bt.style == "backmap/harmonic":
                    f.write(
                        f"bond_coeff {bt.type_id} backmap/harmonic "
                        f"{bt.keyword} {bt.params[0]:.6f} {bt.params[1]:.6f}\n"
                    )
                elif bt.style == "backmap/table":
                    f.write(
                        f"bond_coeff {bt.type_id} backmap/table "
                        f"{bt.keyword} {bt.table_file} {bt.table_keyword}\n"
                    )
            else:
                if bt.style == "harmonic":
                    f.write(f"bond_coeff {bt.type_id} {bt.params[0]:.6f} {bt.params[1]:.6f}\n")
                elif bt.style == "backmap/harmonic":
                    f.write(
                        f"bond_coeff {bt.type_id} "
                        f"{bt.keyword} {bt.params[0]:.6f} {bt.params[1]:.6f}\n"
                    )
                elif bt.style == "backmap/table":
                    f.write(
                        f"bond_coeff {bt.type_id} {bt.keyword} {bt.table_file} {bt.table_keyword}\n"
                    )
        f.write("\n")

        # Angle style
        if system.angle_types:
            if len(angle_styles) > 1:
                f.write(f"angle_style hybrid {' '.join(angle_styles)}\n")
            elif angle_styles:
                f.write(f"angle_style {angle_styles[0]}\n")

            for angtype in system.angle_types:
                if len(angle_styles) > 1:
                    if angtype.style == "harmonic":
                        f.write(
                            f"angle_coeff {angtype.type_id} harmonic "
                            f"{angtype.params[0]:.6f} {angtype.params[1]:.4f}\n"
                        )
                    elif angtype.style == "backmap/harmonic":
                        f.write(
                            f"angle_coeff {angtype.type_id} backmap/harmonic "
                            f"{angtype.keyword} {angtype.params[0]:.6f} {angtype.params[1]:.4f}\n"
                        )
                else:
                    if angtype.style == "harmonic":
                        f.write(
                            f"angle_coeff {angtype.type_id} "
                            f"{angtype.params[0]:.6f} {angtype.params[1]:.4f}\n"
                        )
                    elif angtype.style == "backmap/harmonic":
                        f.write(
                            f"angle_coeff {angtype.type_id} "
                            f"{angtype.keyword} {angtype.params[0]:.6f} {angtype.params[1]:.4f}\n"
                        )
            f.write("\n")

        # Special bonds (exclusions)
        nrexcl = sim.exclusion_nrexcl
        if nrexcl >= 3:
            f.write("special_bonds lj 0.0 0.0 0.0 coul 0.0 0.0 0.0\n\n")
        elif nrexcl == 2:
            f.write("special_bonds lj 0.0 0.0 1.0 coul 0.0 0.0 1.0\n\n")
        elif nrexcl == 1:
            f.write("special_bonds lj 0.0 1.0 1.0 coul 0.0 1.0 1.0\n\n")

        # Groups
        at_type_str = " ".join(str(t) for t in at_type_ids)
        cg_type_str = " ".join(str(t) for t in cg_type_ids)
        f.write(f"group at_atoms type {at_type_str}\n")
        f.write(f"group cg_atoms type {cg_type_str}\n\n")

        # Fix backmap
        nonuniform = "yes" if sim.nonuniform_lambda else "no"
        f.write(
            f"fix bm all backmap cg_type {system.cg_type_id} "
            f"alpha {sim.alpha} lambda0 {sim.initial_resolution} "
            f"nonuniform {nonuniform}\n\n"
        )

        # Integration (AT atoms only)
        f.write("fix integrate at_atoms nve\n")
        if sim.thermostat == "langevin":
            seed = sim.rng_seed if sim.rng_seed > 0 else 48279
            f.write(
                f"fix thermo at_atoms langevin {sim.temperature:.1f} "
                f"{sim.temperature:.1f} {gamma_inv_fs:.1f} {seed}\n"
            )
        f.write("\n")

        # Output
        f.write(f"timestep {timestep_fs:.2f}\n\n")
        f.write(f"thermo {sim.energy_interval}\n")
        f.write("thermo_style custom step temp pe ke etotal press\n\n")
        f.write(
            f"dump traj all custom {sim.trajectory_interval} dump.backmap id mol type x y z f_bm\n"
        )
        f.write("dump_modify traj sort id\n\n")

        # Phase 1: CG equilibration (lambda frozen at 0)
        f.write("# Phase 1: CG equilibration\n")
        f.write("fix_modify bm active no\n")
        f.write(f"run {sim.equilibration_steps}\n\n")

        # Phase 2: Backmapping (lambda ramp 0 → 1)
        f.write("# Phase 2: Backmapping\n")
        ts_backmap = units.time(sim.timestep_backmapping)
        f.write(f"timestep {ts_backmap:.2f}\n")
        f.write("fix_modify bm active yes\n")
        f.write(f"run {backmapping_steps}\n\n")

        # Phase 3: AT production (lambda = 1, CG forces = 0)
        f.write("# Phase 3: AT production\n")
        f.write(f"timestep {timestep_fs:.2f}\n")
        f.write(f"run {sim.production_steps}\n")
