"""LAMMPS data file and input script writers."""

from __future__ import annotations

import math
from typing import IO, TYPE_CHECKING, Any

from . import units
from .builder import DihedralTypeInfo, System
from .network.pbc import max_bond_length as _max_bond_length_from_pbc
from .network.pbc import max_euclidean_bond_length, validate_bond_geometry
from .schema import Settings, SimulationParams

if TYPE_CHECKING:
    from pathlib import Path


def write_lammps_data(system: System, path: Path) -> None:
    """Write a LAMMPS data file (atom_style full)."""
    with open(path, "w") as f:
        f.write("LAMMPS data file for backmapping — generated by backmap-prep\n\n")

        f.write(f"{len(system.atoms)} atoms\n")
        f.write(f"{len(system.bonds)} bonds\n")
        f.write(f"{len(system.angles)} angles\n")
        f.write(f"{len(system.dihedrals)} dihedrals\n")
        f.write("0 impropers\n\n")

        f.write(f"{len(system.atom_types)} atom types\n")
        f.write(f"{len(system.bond_types)} bond types\n")
        f.write(f"{len(system.angle_types)} angle types\n")
        f.write(f"{len(system.dihedral_types)} dihedral types\n")
        f.write("0 improper types\n\n")

        bx, by, bz = system.box
        f.write(f"0.0 {bx:.6f} xlo xhi\n")
        f.write(f"0.0 {by:.6f} ylo yhi\n")
        f.write(f"0.0 {bz:.6f} zlo zhi\n\n")

        # Masses
        f.write("Masses\n\n")
        for at in system.atom_types:
            label = f"# {at.name}" + (" (CG)" if at.is_cg else "")
            f.write(f"{at.type_id} {at.mass:.6f} {label}\n")
        f.write("\n")

        # Atoms — network hybrids use folded coords + image flags; linear systems wrap per atom.
        f.write("Atoms # full\n\n")
        bx, by, bz = system.box
        use_image_flags = (
            system.write_image_flags
            or system.has_cross_bonds
            or system.has_cross_angles
            or system.has_cross_dihedrals
            or system.has_cross_pairs
        )
        wrap_coords = not use_image_flags
        for a in system.atoms:
            if wrap_coords:
                wx = a.x % bx if bx > 0 else a.x
                wy = a.y % by if by > 0 else a.y
                wz = a.z % bz if bz > 0 else a.z
                f.write(
                    f"{a.atom_id} {a.mol_id} {a.type_id} {a.charge:.6f} "
                    f"{wx:.6f} {wy:.6f} {wz:.6f}\n"
                )
            else:
                f.write(
                    f"{a.atom_id} {a.mol_id} {a.type_id} {a.charge:.6f} "
                    f"{a.x:.6f} {a.y:.6f} {a.z:.6f} {a.ix} {a.iy} {a.iz}\n"
                )
        f.write("\n")

        # Bonds
        if system.bonds:
            f.write("Bonds\n\n")
            for b in system.bonds:
                f.write(f"{b.bond_id} {b.type_id} {b.i} {b.j}\n")
            f.write("\n")

        # Angles
        if system.angles:
            f.write("Angles\n\n")
            for ang in system.angles:
                f.write(f"{ang.angle_id} {ang.type_id} {ang.i} {ang.j} {ang.k}\n")
            f.write("\n")

        if system.dihedrals:
            f.write("Dihedrals\n\n")
            for dih in system.dihedrals:
                f.write(f"{dih.dihedral_id} {dih.type_id} {dih.i} {dih.j} {dih.k} {dih.l}\n")
            f.write("\n")

    # Print type mapping tables
    print("\n--- Atom type mapping ---")
    for atype in system.atom_types:
        kind = "CG" if atype.is_cg else "AT"
        print(f"  Type {atype.type_id} = {atype.name} ({kind})")

    print("\n--- Bond type mapping ---")
    for bt in system.bond_types:
        kw = f" {bt.keyword}" if bt.keyword else ""
        extra = f" (table: {bt.table_file})" if bt.table_file else ""
        print(f"  Bond type {bt.type_id} = {bt.style}{kw}{extra}")

    if system.angle_types:
        print("\n--- Angle type mapping ---")
        for angtype in system.angle_types:
            kw = f" {angtype.keyword}" if angtype.keyword else ""
            print(f"  Angle type {angtype.type_id} = {angtype.style}{kw}")

    if system.dihedral_types:
        print("\n--- Dihedral type mapping ---")
        for dihtype in system.dihedral_types:
            kw = f" {dihtype.keyword}" if dihtype.keyword else ""
            extra = f" (table: {dihtype.table_file})" if dihtype.table_file else ""
            print(f"  Dihedral type {dihtype.type_id} = {dihtype.style}{kw}{extra}")


def _min_image_distance(
    x1: float,
    y1: float,
    z1: float,
    x2: float,
    y2: float,
    z2: float,
    box: tuple[float, float, float],
) -> float:
    """Minimum-image distance in an orthorhombic box (Angstrom)."""
    bx, by, bz = box
    dx = abs(x1 - x2)
    dy = abs(y1 - y2)
    dz = abs(z1 - z2)
    if bx > 0:
        dx = min(dx, bx - dx)
    if by > 0:
        dy = min(dy, by - dy)
    if bz > 0:
        dz = min(dz, bz - dz)
    return math.sqrt(dx * dx + dy * dy + dz * dz)


def _max_bond_length(system: System) -> float:
    """Longest bonded distance in the system (minimum-image, Angstrom)."""
    return _max_bond_length_from_pbc(system.atoms, system.bonds, system.box)


def _compute_params(system: System, settings: Settings) -> dict[str, Any]:
    """Pre-compute unit-converted values and style lists used by multiple writers."""
    sim = settings.simulation
    timestep_fs = units.time(sim.timestep)
    lj_cut_ang = units.distance(sim.lj_cutoff)
    cg_cut_ang = units.distance(sim.cg_cutoff)
    coul_cut_ang = units.distance(sim.coulomb_cutoff)
    gamma_inv_fs = units.time(1.0 / sim.thermostat_gamma) if sim.thermostat_gamma > 0 else 100.0
    tdamp_fs = units.time(sim.thermostat_tdamp)
    pressure_atm = units.pressure(sim.pressure)
    pdamp_fs = units.time(sim.barostat_pdamp)
    backmapping_steps = int(1.0 / sim.alpha)
    ts_backmap_fs = units.time(sim.timestep_backmapping)

    cg_type_ids = sorted({at.type_id for at in system.atom_types if at.is_cg})
    at_type_ids = sorted({at.type_id for at in system.atom_types if not at.is_cg})

    has_static_bonds = any(bt.style == "harmonic" for bt in system.bond_types)
    has_backmap_harm = any(bt.style == "backmap/harmonic" for bt in system.bond_types)
    has_backmap_table = any(bt.style == "backmap/table" for bt in system.bond_types)

    bond_styles: list[str] = []
    if has_static_bonds:
        bond_styles.append("harmonic")
    if has_backmap_harm:
        bond_styles.append("backmap/harmonic")
    if has_backmap_table:
        bond_styles.append("backmap/table linear 1000")

    has_static_angles = any(at.style == "harmonic" for at in system.angle_types)
    has_backmap_angles = any(at.style == "backmap/harmonic" for at in system.angle_types)
    has_backmap_angle_table = any(at.style == "backmap/table" for at in system.angle_types)

    angle_styles: list[str] = []
    if has_static_angles:
        angle_styles.append("harmonic")
    if has_backmap_angles:
        angle_styles.append("backmap/harmonic")
    if has_backmap_angle_table:
        angle_styles.append("backmap/table linear 1000")

    has_static_dihedrals = any(dt.style == "ryckaert" for dt in system.dihedral_types)
    has_static_harmonic_dihedrals = any(dt.style == "harmonic" for dt in system.dihedral_types)
    has_static_charmm = any(dt.style == "charmm" for dt in system.dihedral_types)
    has_backmap_rb = any(dt.style == "backmap/ryckaert" for dt in system.dihedral_types)
    has_backmap_harmonic_dihedrals = any(
        dt.style == "backmap/harmonic" for dt in system.dihedral_types
    )
    has_backmap_charmm = any(dt.style == "backmap/charmm" for dt in system.dihedral_types)
    has_backmap_dihedral_table = any(dt.style == "backmap/table" for dt in system.dihedral_types)

    dihedral_styles: list[str] = []
    if has_static_dihedrals:
        dihedral_styles.append("ryckaert")
    if has_static_harmonic_dihedrals:
        dihedral_styles.append("harmonic")
    if has_static_charmm:
        dihedral_styles.append("charmm")
    if has_backmap_rb:
        dihedral_styles.append("backmap/ryckaert")
    if has_backmap_harmonic_dihedrals:
        dihedral_styles.append("backmap/harmonic")
    if has_backmap_charmm:
        dihedral_styles.append("backmap/charmm")
    if has_backmap_dihedral_table:
        dihedral_styles.append("backmap/table linear 1000")

    max_bond_ang = _max_bond_length(system)
    interaction_cutoff_ang = max(lj_cut_ang, cg_cut_ang)
    comm_skin_ang = 1.0
    comm_cutoff_ang = interaction_cutoff_ang + comm_skin_ang
    is_network_hybrid = (
        system.has_cross_bonds
        or system.has_cross_angles
        or system.has_cross_dihedrals
        or system.has_cross_pairs
    )
    if is_network_hybrid and system.write_image_flags:
        max_euclidean_bond_ang = max_euclidean_bond_length(system.atoms, system.bonds)
        # Cured networks (rim135): crosslink bonds can span the box in file
        # coordinates; LAMMPS comm must cover the folded Cartesian extent.
        # Linear polymer melts use min-image cross-CG bonds only — keep lj+cg cutoff.
        bond_extent = max(max_bond_ang, max_euclidean_bond_ang)
        comm_cutoff_ang = max(
            comm_cutoff_ang,
            bond_extent + comm_skin_ang,
        )
        validate_bond_geometry(system, interaction_cutoff_ang)

    return {
        "timestep_fs": timestep_fs,
        "lj_cut_ang": lj_cut_ang,
        "cg_cut_ang": cg_cut_ang,
        "coul_cut_ang": coul_cut_ang,
        "comm_cutoff_ang": comm_cutoff_ang,
        "gamma_inv_fs": gamma_inv_fs,
        "tdamp_fs": tdamp_fs,
        "pressure_atm": pressure_atm,
        "pdamp_fs": pdamp_fs,
        "backmapping_steps": backmapping_steps,
        "ts_backmap_fs": ts_backmap_fs,
        "cg_type_ids": cg_type_ids,
        "at_type_ids": at_type_ids,
        "bond_styles": bond_styles,
        "angle_styles": angle_styles,
        "dihedral_styles": dihedral_styles,
    }


def _format_dihedral_coeff(dihtype: DihedralTypeInfo, dihedral_styles: list[str]) -> str:
    hybrid = len(dihedral_styles) > 1
    if dihtype.style == "ryckaert":
        coeffs = " ".join(f"{value:.6f}" for value in dihtype.params[:6])
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} ryckaert {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {coeffs}\n"
    if dihtype.style == "backmap/ryckaert":
        coeffs = " ".join(f"{value:.6f}" for value in dihtype.params[:6])
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} backmap/ryckaert {dihtype.keyword} {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} {coeffs}\n"
    if dihtype.style == "backmap/table":
        if hybrid:
            return (
                f"dihedral_coeff {dihtype.type_id} backmap/table "
                f"{dihtype.keyword} {dihtype.table_file} {dihtype.table_keyword}\n"
            )
        return (
            f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} "
            f"{dihtype.table_file} {dihtype.table_keyword}\n"
        )
    if dihtype.style == "harmonic":
        k_val, sign_val, n_val = dihtype.params[:3]
        coeffs = f"{k_val:.6f} {int(sign_val)} {int(n_val)}"
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} harmonic {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {coeffs}\n"
    if dihtype.style == "backmap/harmonic":
        k_val, sign_val, n_val = dihtype.params[:3]
        coeffs = f"{k_val:.6f} {int(sign_val)} {int(n_val)}"
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} backmap/harmonic {dihtype.keyword} {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} {coeffs}\n"
    if dihtype.style == "charmm":
        k_val, n_val, delta = dihtype.params[:3]
        shift = int(round(delta))
        coeffs = f"{k_val:.6f} {int(n_val)} {shift} 1.0"
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} charmm {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {coeffs}\n"
    if dihtype.style == "backmap/charmm":
        k_val, n_val, delta = dihtype.params[:3]
        shift = int(round(delta))
        coeffs = f"{k_val:.6f} {int(n_val)} {shift} 1.0"
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} backmap/charmm {dihtype.keyword} {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} {coeffs}\n"
    return ""


def _write_initial_velocities(f: IO[str], sim: SimulationParams, params: dict[str, Any]) -> None:
    temp = sim.temperature
    seed = sim.rng_seed if sim.rng_seed > 0 else 48279
    f.write(f"# Initial velocities at T={temp:.1f} K\n")
    f.write(f"velocity all create {temp:.1f} {seed} dist gaussian mom yes rot yes\n\n")


def _write_cap_force(f: IO[str], sim: SimulationParams) -> None:
    if sim.cap_force is None or sim.cap_force <= 0:
        return
    fmax = units.force(sim.cap_force)
    if sim.cap_force_ramp is not None and sim.cap_force_ramp != 0.0:
        ramp = units.force(sim.cap_force_ramp)
        f.write(f"fix cap all backmap/capforce {fmax:.4f} ramp {ramp:.6f}\n\n")
    else:
        f.write(f"fix cap all backmap/capforce {fmax:.4f}\n\n")


def _write_integration(f: IO[str], sim: SimulationParams, params: dict[str, Any]) -> None:
    """Write integration fixes (thermostat / barostat) for AT atoms."""
    temp = sim.temperature
    seed = sim.rng_seed if sim.rng_seed > 0 else 48279

    if sim.thermostat == "nose_hoover":
        tdamp = params["tdamp_fs"]
        if sim.ensemble == "npt":
            p = params["pressure_atm"]
            pdamp = params["pdamp_fs"]
            f.write(
                f"fix integrate at_atoms npt temp {temp:.1f} {temp:.1f} {tdamp:.1f} "
                f"iso {p:.1f} {p:.1f} {pdamp:.1f}\n\n"
            )
        else:
            f.write(f"fix integrate at_atoms nvt temp {temp:.1f} {temp:.1f} {tdamp:.1f}\n\n")
    else:
        # Langevin: NVE + stochastic thermostat
        f.write("fix integrate at_atoms nve\n")
        f.write(
            f"fix thermo at_atoms langevin {temp:.1f} "
            f"{temp:.1f} {params['gamma_inv_fs']:.1f} {seed}\n\n"
        )


def _write_setup(
    f: IO[str],
    system: System,
    settings: Settings,
    params: dict[str, Any],
    data_filename: str,
    *,
    use_read_data: bool = True,
) -> None:
    """Write the shared setup block (styles, coefficients, groups, fixes)."""
    sim = settings.simulation
    bond_styles = params["bond_styles"]
    angle_styles = params["angle_styles"]
    dihedral_styles = params["dihedral_styles"]

    if use_read_data:
        f.write(f"read_data {data_filename}\n\n")
        if system.write_image_flags:
            f.write("reset_atoms image all\n\n")

    f.write(f"comm_modify cutoff {params['comm_cutoff_ang']:.2f}\n\n")

    # Pair style
    f.write(
        f"pair_style backmap {params['lj_cut_ang']:.2f} lj/cut/coul/cut "
        f"{params['lj_cut_ang']:.2f} {params['coul_cut_ang']:.2f} "
        f"{params['cg_cut_ang']:.2f} table linear 1000\n"
    )
    for pt in system.pair_types:
        if pt.kind == "atomistic":
            f.write(f"pair_coeff {pt.itype} {pt.jtype} atomistic {pt.epsilon:.6f} {pt.sigma:.6f}\n")
        elif pt.kind == "cg":
            if pt.table_file:
                f.write(f"pair_coeff {pt.itype} {pt.jtype} cg {pt.table_file} {pt.table_keyword}\n")
            else:
                f.write(f"pair_coeff {pt.itype} {pt.jtype} cg 0.0 0.0\n")
        else:
            f.write(f"pair_coeff {pt.itype} {pt.jtype} none\n")
    f.write("\n")

    # Bond style
    if len(bond_styles) > 1:
        f.write(f"bond_style hybrid {' '.join(bond_styles)}\n")
    elif bond_styles:
        f.write(f"bond_style {bond_styles[0]}\n")

    for bt in system.bond_types:
        if len(bond_styles) > 1:
            if bt.style == "harmonic":
                f.write(f"bond_coeff {bt.type_id} harmonic {bt.params[0]:.6f} {bt.params[1]:.6f}\n")
            elif bt.style == "backmap/harmonic":
                f.write(
                    f"bond_coeff {bt.type_id} backmap/harmonic "
                    f"{bt.keyword} {bt.params[0]:.6f} {bt.params[1]:.6f}\n"
                )
            elif bt.style == "backmap/table":
                f.write(
                    f"bond_coeff {bt.type_id} backmap/table "
                    f"{bt.keyword} {bt.table_file} {bt.table_keyword}\n"
                )
        else:
            if bt.style == "harmonic":
                f.write(f"bond_coeff {bt.type_id} {bt.params[0]:.6f} {bt.params[1]:.6f}\n")
            elif bt.style == "backmap/harmonic":
                f.write(
                    f"bond_coeff {bt.type_id} {bt.keyword} {bt.params[0]:.6f} {bt.params[1]:.6f}\n"
                )
            elif bt.style == "backmap/table":
                f.write(
                    f"bond_coeff {bt.type_id} {bt.keyword} {bt.table_file} {bt.table_keyword}\n"
                )
    f.write("\n")

    # Angle style
    if system.angle_types:
        if len(angle_styles) > 1:
            f.write(f"angle_style hybrid {' '.join(angle_styles)}\n")
        elif angle_styles:
            f.write(f"angle_style {angle_styles[0]}\n")

        for angtype in system.angle_types:
            if len(angle_styles) > 1:
                if angtype.style == "harmonic":
                    f.write(
                        f"angle_coeff {angtype.type_id} harmonic "
                        f"{angtype.params[0]:.6f} {angtype.params[1]:.4f}\n"
                    )
                elif angtype.style == "backmap/harmonic":
                    f.write(
                        f"angle_coeff {angtype.type_id} backmap/harmonic "
                        f"{angtype.keyword} {angtype.params[0]:.6f} {angtype.params[1]:.4f}\n"
                    )
                elif angtype.style == "backmap/table":
                    f.write(
                        f"angle_coeff {angtype.type_id} backmap/table "
                        f"{angtype.keyword} {angtype.table_file} {angtype.table_keyword}\n"
                    )
            else:
                if angtype.style == "harmonic":
                    f.write(
                        f"angle_coeff {angtype.type_id} "
                        f"{angtype.params[0]:.6f} {angtype.params[1]:.4f}\n"
                    )
                elif angtype.style == "backmap/harmonic":
                    f.write(
                        f"angle_coeff {angtype.type_id} "
                        f"{angtype.keyword} {angtype.params[0]:.6f} {angtype.params[1]:.4f}\n"
                    )
                elif angtype.style == "backmap/table":
                    f.write(
                        f"angle_coeff {angtype.type_id} "
                        f"{angtype.keyword} {angtype.table_file} {angtype.table_keyword}\n"
                    )
        f.write("\n")

    # Dihedral style
    if system.dihedral_types:
        if len(dihedral_styles) > 1:
            f.write(f"dihedral_style hybrid {' '.join(dihedral_styles)}\n")
        elif dihedral_styles:
            f.write(f"dihedral_style {dihedral_styles[0]}\n")

        for dihtype in system.dihedral_types:
            coeff = _format_dihedral_coeff(dihtype, dihedral_styles)
            f.write(coeff)
        f.write("\n")

    # Special bonds (exclusions)
    nrexcl = sim.exclusion_nrexcl
    if nrexcl >= 3:
        f.write("special_bonds lj 0.0 0.0 0.0 coul 0.0 0.0 0.0\n\n")
    elif nrexcl == 2:
        f.write("special_bonds lj 0.0 0.0 1.0 coul 0.0 0.0 1.0\n\n")
    elif nrexcl == 1:
        f.write("special_bonds lj 0.0 1.0 1.0 coul 0.0 1.0 1.0\n\n")

    # Groups
    at_type_str = " ".join(str(t) for t in params["at_type_ids"])
    cg_type_str = " ".join(str(t) for t in params["cg_type_ids"])
    f.write(f"group at_atoms type {at_type_str}\n")
    f.write(f"group cg_atoms type {cg_type_str}\n\n")
    f.write("neigh_modify delay 0 every 1 check yes\n\n")

    _write_initial_velocities(f, sim, params)

    # Integration (AT atoms only) — must be defined BEFORE fix backmap so
    # that NVE/NVT initial_integrate runs first, updating AT positions before
    # fix backmap tracks the CG→COM.
    _write_integration(f, sim, params)

    # Fix backmap
    nonuniform = "yes" if sim.nonuniform_lambda else "no"
    cg_type_fix_str = " ".join(str(t) for t in params["cg_type_ids"])
    f.write(
        f"fix bm all backmap cg_type {cg_type_fix_str} "
        f"alpha {sim.alpha} lambda0 {sim.initial_resolution} "
        f"nonuniform {nonuniform}\n\n"
    )

    if system.has_cross_pairs:
        f.write(
            f"fix pairs all backmap/pairs at file {system.cross_pairs_file} "
            f"cut {params['lj_cut_ang']:.6f}\n\n"
        )

    _write_cap_force(f, sim)

    # Temperature compute on AT atoms only (CG atoms have zero velocity,
    # which would dilute the reported temperature).
    f.write("compute at_temp at_atoms temp\n\n")

    # First dynamics segment always uses the backmapping timestep. Using the
    # (often larger) production timestep during λ-frozen hybrid relaxation can
    # blow up before the ramp starts (missing bonded neighbors on dense melts).
    init_ts = params["ts_backmap_fs"]
    f.write(f"timestep {init_ts:.2f}\n\n")
    f.write(f"thermo {sim.energy_interval}\n")
    f.write("thermo_style custom step temp pe ke etotal press f_bm\n")
    f.write("thermo_modify colname f_bm lambda\n")
    f.write("thermo_modify temp at_temp\n\n")
    f.write(f"dump traj all custom {sim.trajectory_interval} dump.backmap id mol type x y z f_bm\n")
    f.write("dump_modify traj sort id\n\n")


def _write_restart_cmd(f: IO[str], restart_interval: int) -> None:
    """Write the LAMMPS restart command for alternating checkpoint files."""
    f.write(f"restart {restart_interval} restart.backmap restart.backmap2\n")


def write_cross_pairs_file(system: System, path: Path) -> None:
    """Write explicit 1–4 LJ pairs for fix backmap/pairs."""
    with open(path, "w") as f:
        f.write(f"{len(system.cross_pairs)}\n")
        for pair in system.cross_pairs:
            f.write(f"{pair.i} {pair.j} {pair.sigma:.6f} {pair.epsilon:.6f}\n")


def write_lammps_input(
    system: System,
    settings: Settings,
    path: Path,
    data_filename: str,
) -> None:
    """Write a LAMMPS input script for backmapping.

    When ``settings.simulation.restart_interval`` is set, also generates
    per-phase scripts and a shared setup include file.
    """
    sim = settings.simulation
    params = _compute_params(system, settings)
    restart = sim.restart_interval

    with open(path, "w") as f:
        f.write("# LAMMPS input for backmapping — generated by backmap-prep\n")
        f.write("# Reference: Krajniak et al., JCTC 2016, DOI: 10.1021/acs.jctc.6b00595\n")
        f.write("#            Krajniak, Zhang et al., JCC 2018, DOI: 10.1002/jcc.25129\n\n")

        f.write("units real\n")
        f.write("atom_style full\n")
        f.write("boundary p p p\n\n")

        _write_setup(f, system, settings, params, data_filename)

        if restart:
            _write_restart_cmd(f, restart)
            f.write("\n")

        if sim.equilibration_steps > 0:
            f.write(
                "# Phase 1: CG equilibration (λ frozen — optional if CG was pre-equilibrated)\n"
            )
            f.write("fix_modify bm active no\n")
            f.write(f"run {sim.equilibration_steps}\n")
            if restart:
                f.write("write_restart restart.backmap\n")
                f.write("shell echo done > phase_1.done\n")
            f.write("\n")

        # Backmapping: λ 0 → 1
        if sim.equilibration_steps > 0:
            f.write("# Phase 2: Backmapping\n")
            f.write(f"timestep {params['ts_backmap_fs']:.2f}\n")
        else:
            f.write("# Backmapping: λ 0 → 1\n")
        f.write("fix_modify bm active yes\n")
        f.write(f"run {params['backmapping_steps']}\n")
        if restart:
            f.write("write_restart restart.backmap\n")
            if sim.equilibration_steps > 0:
                f.write("shell echo done > phase_2.done\n")
            else:
                f.write("shell echo done > phase_1.done\n")
        f.write("\n")
        hybrid_out = data_filename.replace(".data", "_hybrid.data")
        f.write(f"write_data {hybrid_out}\n")

        if sim.production_steps > 0:
            if sim.equilibration_steps > 0:
                f.write("\n# Phase 3: AT production (optional post-backmap)\n")
            else:
                f.write("\n# AT production (λ = 1) in the same run\n")
            f.write(f"timestep {params['timestep_fs']:.2f}\n")
            f.write(f"run {sim.production_steps}\n")
            if restart:
                if sim.equilibration_steps > 0:
                    f.write("shell echo done > phase_3.done\n")
                else:
                    f.write("shell echo done > phase_2.done\n")
            final_out = data_filename.replace(".data", "_final.data")
            f.write(f"\nwrite_data {final_out}\n")

    # Generate per-phase scripts when restart is enabled
    if restart:
        _write_restart_scripts(system, settings, path, data_filename, params)


def _write_restart_scripts(
    system: System,
    settings: Settings,
    master_path: Path,
    data_filename: str,
    params: dict[str, Any],
) -> None:
    """Generate the setup include and per-phase restart scripts."""
    sim = settings.simulation
    restart = sim.restart_interval
    assert restart is not None

    parent = master_path.parent
    stem = master_path.name  # e.g. "in.backmap"
    phase3_path = parent / f"{stem}.phase3"

    # --- in.<prefix>.setup ---
    setup_path = parent / f"{stem}.setup"
    with open(setup_path, "w") as f:
        f.write("# Shared setup — generated by backmap-prep (do not edit)\n\n")
        _write_setup(f, system, settings, params, data_filename, use_read_data=False)
        _write_restart_cmd(f, restart)
        f.write("\n")

    setup_name = setup_path.name
    hybrid_out = data_filename.replace(".data", "_hybrid.data")
    phase2_path = parent / f"{stem}.phase2"

    if sim.equilibration_steps == 0:
        if phase3_path.exists():
            phase3_path.unlink()

        # --- in.<prefix>.phase1 — backmapping only ---
        with open(parent / f"{stem}.phase1", "w") as f:
            f.write("# Phase 1: Backmapping λ 0→1 (restart-aware) — generated by backmap-prep\n\n")
            f.write("units real\n")
            f.write("atom_style full\n")
            f.write("boundary p p p\n\n")
            f.write(f"read_data {data_filename}\n\n")
            f.write(f"include {setup_name}\n\n")
            f.write("# Backmapping: λ 0 → 1\n")
            f.write(f"timestep {params['ts_backmap_fs']:.2f}\n")
            f.write("fix_modify bm active yes\n")
            f.write(f"run {params['backmapping_steps']}\n")
            f.write("write_restart restart.backmap\n")
            f.write(f"write_data {hybrid_out}\n")
            f.write("shell echo done > phase_1.done\n")

        if sim.production_steps > 0:
            with open(phase2_path, "w") as f:
                f.write("# Phase 2: AT production (restart-aware) — generated by backmap-prep\n\n")
                f.write("units real\n")
                f.write("atom_style full\n")
                f.write("boundary p p p\n\n")
                f.write("read_restart restart.backmap\n\n")
                f.write(f"include {setup_name}\n\n")
                f.write("# AT production (λ = 1)\n")
                f.write(f"timestep {params['timestep_fs']:.2f}\n")
                f.write(f"run {sim.production_steps}\n")
                f.write("shell echo done > phase_2.done\n")
        elif phase2_path.exists():
            phase2_path.unlink()
        return

    # --- in.<prefix>.phase1 — CG equilibration ---
    with open(parent / f"{stem}.phase1", "w") as f:
        f.write("# Phase 1: CG equilibration (restart-aware) — generated by backmap-prep\n\n")
        f.write("units real\n")
        f.write("atom_style full\n")
        f.write("boundary p p p\n\n")
        f.write(f"read_data {data_filename}\n\n")
        f.write(f"include {setup_name}\n\n")
        f.write("# Phase 1: CG equilibration\n")
        f.write("fix_modify bm active no\n")
        f.write(f"run {sim.equilibration_steps}\n")
        f.write("write_restart restart.backmap\n")
        f.write("shell echo done > phase_1.done\n")

    # --- in.<prefix>.phase2 — backmapping ---
    with open(parent / f"{stem}.phase2", "w") as f:
        f.write("# Phase 2: Backmapping (restart-aware) — generated by backmap-prep\n\n")
        f.write("units real\n")
        f.write("atom_style full\n")
        f.write("boundary p p p\n\n")
        f.write("read_restart restart.backmap\n\n")
        f.write(f"include {setup_name}\n\n")
        f.write("# Phase 2: Backmapping\n")
        f.write(f"timestep {params['ts_backmap_fs']:.2f}\n")
        f.write("fix_modify bm active yes\n")
        f.write(f"run {params['backmapping_steps']}\n")
        f.write("write_restart restart.backmap\n")
        f.write(f"write_data {hybrid_out}\n")
        f.write("shell echo done > phase_2.done\n")

    if sim.production_steps > 0:
        with open(phase3_path, "w") as f:
            f.write("# Phase 3: AT production (restart-aware) — generated by backmap-prep\n\n")
            f.write("units real\n")
            f.write("atom_style full\n")
            f.write("boundary p p p\n\n")
            f.write("read_restart restart.backmap\n\n")
            f.write(f"include {setup_name}\n\n")
            f.write("# Phase 3: AT production\n")
            f.write(f"timestep {params['timestep_fs']:.2f}\n")
            f.write(f"run {sim.production_steps}\n")
            f.write("shell echo done > phase_3.done\n")
    elif phase3_path.exists():
        phase3_path.unlink()
