"""LAMMPS data file and input script writers."""

from __future__ import annotations

import math
from pathlib import Path
from typing import IO, Any

from . import units
from .builder import DihedralTypeInfo, System
from .network.pbc import max_interaction_extent, validate_bond_geometry
from .schema import Settings, SimulationParams


def normalize_file_end(path: Path) -> None:
    """End a generated text file with exactly one newline and no trailing blanks."""
    lines = [line.rstrip() for line in path.read_text().splitlines()]
    while lines and not lines[-1]:
        lines.pop()
    path.write_text("\n".join(lines) + "\n")


def write_lammps_data(system: System, path: Path) -> None:
    """Write a LAMMPS data file (atom_style full)."""
    with open(path, "w") as f:
        f.write("LAMMPS data file for backmapping — generated by backmap-prep\n\n")

        f.write(f"{len(system.atoms)} atoms\n")
        f.write(f"{len(system.bonds)} bonds\n")
        f.write(f"{len(system.angles)} angles\n")
        f.write(f"{len(system.dihedrals)} dihedrals\n")
        f.write(f"{len(system.impropers)} impropers\n\n")

        f.write(f"{len(system.atom_types)} atom types\n")
        f.write(f"{len(system.bond_types)} bond types\n")
        f.write(f"{len(system.angle_types)} angle types\n")
        f.write(f"{len(system.dihedral_types)} dihedral types\n")
        f.write(f"{len(system.improper_types)} improper types\n\n")

        bx, by, bz = system.box
        f.write(f"0.0 {bx:.6f} xlo xhi\n")
        f.write(f"0.0 {by:.6f} ylo yhi\n")
        f.write(f"0.0 {bz:.6f} zlo zhi\n\n")

        # Masses
        f.write("Masses\n\n")
        for at in system.atom_types:
            label = f"# {at.name}" + (" (CG)" if at.is_cg else "")
            f.write(f"{at.type_id} {at.mass:.6f} {label}\n")
        f.write("\n")

        # Atoms — network hybrids use folded coords + image flags; linear systems wrap per atom.
        f.write("Atoms # full\n\n")
        bx, by, bz = system.box
        use_image_flags = (
            system.write_image_flags
            or system.has_cross_bonds
            or system.has_cross_angles
            or system.has_cross_dihedrals
            or system.has_cross_pairs
        )
        wrap_coords = not use_image_flags
        for a in system.atoms:
            if wrap_coords:
                wx = a.x % bx if bx > 0 else a.x
                wy = a.y % by if by > 0 else a.y
                wz = a.z % bz if bz > 0 else a.z
                f.write(
                    f"{a.atom_id} {a.mol_id} {a.type_id} {a.charge:.10g} "
                    f"{wx:.6f} {wy:.6f} {wz:.6f}\n"
                )
            else:
                f.write(
                    f"{a.atom_id} {a.mol_id} {a.type_id} {a.charge:.10g} "
                    f"{a.x:.6f} {a.y:.6f} {a.z:.6f} {a.ix} {a.iy} {a.iz}\n"
                )
        f.write("\n")

        # Bonds
        if system.bonds:
            f.write("Bonds\n\n")
            for b in system.bonds:
                f.write(f"{b.bond_id} {b.type_id} {b.i} {b.j}\n")
            f.write("\n")

        # Angles
        if system.angles:
            f.write("Angles\n\n")
            for ang in system.angles:
                f.write(f"{ang.angle_id} {ang.type_id} {ang.i} {ang.j} {ang.k}\n")
            f.write("\n")

        if system.dihedrals:
            f.write("Dihedrals\n\n")
            for dih in system.dihedrals:
                f.write(f"{dih.dihedral_id} {dih.type_id} {dih.i} {dih.j} {dih.k} {dih.l}\n")
            f.write("\n")

        if system.impropers:
            f.write("Impropers\n\n")
            for imp in system.impropers:
                f.write(f"{imp.improper_id} {imp.type_id} {imp.i} {imp.j} {imp.k} {imp.l}\n")
            f.write("\n")

    # Print type mapping tables
    print("\n--- Atom type mapping ---")
    for atype in system.atom_types:
        kind = "CG" if atype.is_cg else "AT"
        print(f"  Type {atype.type_id} = {atype.name} ({kind})")

    print("\n--- Bond type mapping ---")
    for bt in system.bond_types:
        kw = f" {bt.keyword}" if bt.keyword else ""
        extra = f" (table: {bt.table_file})" if bt.table_file else ""
        print(f"  Bond type {bt.type_id} = {bt.style}{kw}{extra}")

    if system.angle_types:
        print("\n--- Angle type mapping ---")
        for angtype in system.angle_types:
            kw = f" {angtype.keyword}" if angtype.keyword else ""
            print(f"  Angle type {angtype.type_id} = {angtype.style}{kw}")

    if system.dihedral_types:
        print("\n--- Dihedral type mapping ---")
        for dihtype in system.dihedral_types:
            kw = f" {dihtype.keyword}" if dihtype.keyword else ""
            extra = f" (table: {dihtype.table_file})" if dihtype.table_file else ""
            print(f"  Dihedral type {dihtype.type_id} = {dihtype.style}{kw}{extra}")
    normalize_file_end(path)


def _min_image_distance(
    x1: float,
    y1: float,
    z1: float,
    x2: float,
    y2: float,
    z2: float,
    box: tuple[float, float, float],
) -> float:
    """Minimum-image distance in an orthorhombic box (Angstrom)."""
    bx, by, bz = box
    dx = abs(x1 - x2)
    dy = abs(y1 - y2)
    dz = abs(z1 - z2)
    if bx > 0:
        dx = min(dx, bx - dx)
    if by > 0:
        dy = min(dy, by - dy)
    if bz > 0:
        dz = min(dz, bz - dz)
    return math.sqrt(dx * dx + dy * dy + dz * dz)


def _compute_params(system: System, settings: Settings) -> dict[str, Any]:
    """Pre-compute unit-converted values and style lists used by multiple writers."""
    sim = settings.simulation
    timestep_fs = units.time(sim.timestep)
    lj_cut_ang = units.distance(sim.lj_cutoff)
    cg_cut_ang = units.distance(sim.cg_cutoff)
    coul_cut_ang = units.distance(sim.coulomb_cutoff)
    gamma_inv_fs = units.time(1.0 / sim.thermostat_gamma) if sim.thermostat_gamma > 0 else 100.0
    tdamp_fs = units.time(sim.thermostat_tdamp)
    pressure_atm = units.pressure(sim.pressure)
    pdamp_fs = units.time(sim.barostat_pdamp)
    backmapping_steps = int(1.0 / sim.alpha)
    ts_backmap_fs = units.time(sim.timestep_backmapping)

    cg_type_ids = sorted({at.type_id for at in system.atom_types if at.is_cg})
    at_type_ids = sorted({at.type_id for at in system.atom_types if not at.is_cg})

    has_static_bonds = any(bt.style == "harmonic" for bt in system.bond_types)
    has_backmap_harm = any(bt.style == "backmap/harmonic" for bt in system.bond_types)
    has_backmap_table = any(bt.style == "backmap/table" for bt in system.bond_types)

    bond_styles: list[str] = []
    if has_static_bonds:
        bond_styles.append("harmonic")
    if has_backmap_harm:
        bond_styles.append("backmap/harmonic")
    if has_backmap_table:
        bond_styles.append("backmap/table linear 1000")

    has_static_angles = any(at.style == "harmonic" for at in system.angle_types)
    has_backmap_angles = any(at.style == "backmap/harmonic" for at in system.angle_types)
    has_backmap_angle_table = any(at.style == "backmap/table" for at in system.angle_types)
    has_backmap_ub = any(at.style == "backmap/charmm" for at in system.angle_types)

    angle_styles: list[str] = []
    if has_static_angles:
        angle_styles.append("harmonic")
    if has_backmap_angles:
        angle_styles.append("backmap/harmonic")
    if has_backmap_ub:
        angle_styles.append("backmap/charmm")
    if has_backmap_angle_table:
        angle_styles.append("backmap/table linear 1000")

    has_static_dihedrals = any(dt.style == "ryckaert" for dt in system.dihedral_types)
    has_static_harmonic_dihedrals = any(dt.style == "harmonic" for dt in system.dihedral_types)
    has_static_charmm = any(dt.style == "charmm" for dt in system.dihedral_types)
    has_backmap_rb = any(dt.style == "backmap/ryckaert" for dt in system.dihedral_types)
    has_backmap_harmonic_dihedrals = any(
        dt.style == "backmap/harmonic" for dt in system.dihedral_types
    )
    has_backmap_charmm = any(dt.style == "backmap/charmm" for dt in system.dihedral_types)
    has_backmap_dihedral_table = any(dt.style == "backmap/table" for dt in system.dihedral_types)

    dihedral_styles: list[str] = []
    if has_static_dihedrals:
        dihedral_styles.append("ryckaert")
    if has_static_harmonic_dihedrals:
        dihedral_styles.append("harmonic")
    if has_static_charmm:
        dihedral_styles.append("charmm")
    if has_backmap_rb:
        dihedral_styles.append("backmap/ryckaert")
    if has_backmap_harmonic_dihedrals:
        dihedral_styles.append("backmap/harmonic")
    if has_backmap_charmm:
        dihedral_styles.append("backmap/charmm")
    if any(dt.style == "backmap/fourier" for dt in system.dihedral_types):
        dihedral_styles.append("backmap/fourier")
    if has_backmap_dihedral_table:
        dihedral_styles.append("backmap/table linear 1000")

    interaction_cutoff_ang = max(lj_cut_ang, cg_cut_ang)
    comm_skin_ang = 1.0
    comm_cutoff_ang = interaction_cutoff_ang + comm_skin_ang
    # Ghost atoms must cover the pair cutoff and the minimum-image extent of
    # every bonded term and bead (see pbc.max_interaction_extent).
    comm_cutoff_ang = max(interaction_cutoff_ang, max_interaction_extent(system)) + comm_skin_ang
    if system.write_image_flags:
        validate_bond_geometry(system, interaction_cutoff_ang)

    return {
        "timestep_fs": timestep_fs,
        "lj_cut_ang": lj_cut_ang,
        "cg_cut_ang": cg_cut_ang,
        "coul_cut_ang": coul_cut_ang,
        "comm_cutoff_ang": comm_cutoff_ang,
        "gamma_inv_fs": gamma_inv_fs,
        "tdamp_fs": tdamp_fs,
        "pressure_atm": pressure_atm,
        "pdamp_fs": pdamp_fs,
        "backmapping_steps": backmapping_steps,
        "ts_backmap_fs": ts_backmap_fs,
        "cg_type_ids": cg_type_ids,
        "at_type_ids": at_type_ids,
        "bond_styles": bond_styles,
        "angle_styles": angle_styles,
        "dihedral_styles": dihedral_styles,
        "apb_by_cg_type": system.apb_by_cg_type,
    }


# special_bonds factor that keeps a pair in the neighbor list but counts as
# excluded in pair_style backmap (below its 1e-30 threshold)
_SPECIAL_TINY = "1.0e-100"


def _special_weights(nrexcl: int) -> list[str]:
    return ["0.0" if level <= nrexcl else "1.0" for level in (1, 2, 3)]


def _special_bonds_split(nrexcl_at: int, nrexcl_cg: int) -> str:
    """special_bonds for AT exclusions; CG pairs get theirs through cg_special.

    A level the AT side excludes but the CG side keeps gets a tiny nonzero
    factor, so LAMMPS keeps the pair in the neighbor list for cg_special.
    """
    at, cg = _special_weights(nrexcl_at), _special_weights(nrexcl_cg)
    factors = [
        _SPECIAL_TINY if a == "0.0" and c == "1.0" else a for a, c in zip(at, cg, strict=True)
    ]
    joined = " ".join(factors)
    return f"special_bonds lj {joined} coul {joined}\n\n"


def _cg_special(sim: SimulationParams) -> str:
    if sim.exclusion_nrexcl_cg is None or sim.exclusion_nrexcl_cg == sim.exclusion_nrexcl:
        return ""
    return " cg_special " + " ".join(_special_weights(sim.exclusion_nrexcl_cg))


def _format_dihedral_coeff(dihtype: DihedralTypeInfo, dihedral_styles: list[str]) -> str:
    hybrid = len(dihedral_styles) > 1
    if dihtype.style == "ryckaert":
        coeffs = " ".join(f"{value:.10g}" for value in dihtype.params[:6])
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} ryckaert {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {coeffs}\n"
    if dihtype.style == "backmap/ryckaert":
        coeffs = " ".join(f"{value:.10g}" for value in dihtype.params[:6])
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} backmap/ryckaert {dihtype.keyword} {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} {coeffs}\n"
    if dihtype.style == "backmap/table":
        if hybrid:
            return (
                f"dihedral_coeff {dihtype.type_id} backmap/table "
                f"{dihtype.keyword} {dihtype.table_file} {dihtype.table_keyword}\n"
            )
        return (
            f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} "
            f"{dihtype.table_file} {dihtype.table_keyword}\n"
        )
    if dihtype.style == "harmonic":
        k_val, sign_val, n_val = dihtype.params[:3]
        coeffs = f"{k_val:.10g} {int(sign_val)} {int(n_val)}"
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} harmonic {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {coeffs}\n"
    if dihtype.style == "backmap/harmonic":
        k_val, sign_val, n_val = dihtype.params[:3]
        coeffs = f"{k_val:.10g} {int(sign_val)} {int(n_val)}"
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} backmap/harmonic {dihtype.keyword} {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} {coeffs}\n"
    if dihtype.style == "charmm":
        k_val, n_val, delta = dihtype.params[:3]
        shift = round(delta)
        coeffs = f"{k_val:.10g} {int(n_val)} {shift} 1.0"
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} charmm {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {coeffs}\n"
    if dihtype.style == "backmap/fourier":
        m = int(dihtype.params[0])
        terms = dihtype.params[1 : 1 + 3 * m]
        coeffs = f"{m} " + " ".join(
            f"{terms[3 * t]:.10g} {int(terms[3 * t + 1])} {terms[3 * t + 2]:.10g}" for t in range(m)
        )
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} backmap/fourier {dihtype.keyword} {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} {coeffs}\n"
    if dihtype.style == "backmap/charmm":
        k_val, n_val, delta = dihtype.params[:3]
        shift = round(delta)
        coeffs = f"{k_val:.10g} {int(n_val)} {shift} 1.0"
        if hybrid:
            return f"dihedral_coeff {dihtype.type_id} backmap/charmm {dihtype.keyword} {coeffs}\n"
        return f"dihedral_coeff {dihtype.type_id} {dihtype.keyword} {coeffs}\n"
    return ""


def _write_initial_velocities(f: IO[str], sim: SimulationParams, params: dict[str, Any]) -> None:
    temp = sim.temperature
    seed = sim.rng_seed if sim.rng_seed > 0 else 48279
    f.write(f"# Initial velocities at T={temp:.1f} K\n")
    f.write(f"velocity all create {temp:.1f} {seed} dist gaussian mom yes rot yes\n\n")


def _write_cap_force(f: IO[str], sim: SimulationParams) -> None:
    if sim.cap_force is None or sim.cap_force <= 0:
        return
    fmax = units.force(sim.cap_force)
    if sim.cap_force_ramp is not None and sim.cap_force_ramp != 0.0:
        ramp = units.force(sim.cap_force_ramp)
        f.write(f"fix cap all backmap/capforce {fmax:.4f} ramp {ramp:.10g}\n\n")
    else:
        f.write(f"fix cap all backmap/capforce {fmax:.4f}\n\n")


def _write_integration(f: IO[str], sim: SimulationParams, params: dict[str, Any]) -> None:
    """Write integration fixes (thermostat / barostat) for AT atoms."""
    temp = sim.temperature
    seed = sim.rng_seed if sim.rng_seed > 0 else 48279

    if sim.thermostat == "nose_hoover":
        tdamp = params["tdamp_fs"]
        if sim.ensemble == "npt":
            p = params["pressure_atm"]
            pdamp = params["pdamp_fs"]
            f.write(
                f"fix integrate at_atoms npt temp {temp:.1f} {temp:.1f} {tdamp:.1f} "
                f"iso {p:.1f} {p:.1f} {pdamp:.1f}\n\n"
            )
        else:
            f.write(f"fix integrate at_atoms nvt temp {temp:.1f} {temp:.1f} {tdamp:.1f}\n\n")
    else:
        # Langevin: NVE + stochastic thermostat
        f.write("fix integrate at_atoms nve\n")
        f.write(
            f"fix thermo at_atoms langevin {temp:.1f} "
            f"{temp:.1f} {params['gamma_inv_fs']:.1f} {seed}\n\n"
        )


def _write_forcefield(
    f: IO[str],
    system: System,
    settings: Settings,
    params: dict[str, Any],
) -> None:
    """Force-field block: comm cutoff, styles, coefficients, special_bonds, groups.

    Written to ``<prefix>.ff.lmp`` and included by the generated input and by
    any hand-written protocol, so no script restates coefficients.
    """
    sim = settings.simulation
    bond_styles = params["bond_styles"]
    angle_styles = params["angle_styles"]
    dihedral_styles = params["dihedral_styles"]

    f.write(f"comm_modify cutoff {params['comm_cutoff_ang']:.2f}\n\n")

    # Pair style
    f.write(
        f"pair_style backmap {params['lj_cut_ang']:.2f} lj/cut/coul/cut "
        f"{params['lj_cut_ang']:.2f} {params['coul_cut_ang']:.2f} "
        f"{params['cg_cut_ang']:.2f} table linear 1000{_cg_special(sim)}\n"
    )
    for pt in system.pair_types:
        if pt.kind == "atomistic":
            f.write(
                f"pair_coeff {pt.itype} {pt.jtype} atomistic {pt.epsilon:.10g} {pt.sigma:.10g}\n"
            )
        elif pt.kind == "cg":
            if pt.table_file:
                f.write(f"pair_coeff {pt.itype} {pt.jtype} cg {pt.table_file} {pt.table_keyword}\n")
            else:
                f.write(f"pair_coeff {pt.itype} {pt.jtype} cg 0.0 0.0\n")
        else:
            f.write(f"pair_coeff {pt.itype} {pt.jtype} none\n")
    f.write("\n")

    # Bond style
    if len(bond_styles) > 1:
        f.write(f"bond_style hybrid {' '.join(bond_styles)}\n")
    elif bond_styles:
        f.write(f"bond_style {bond_styles[0]}\n")

    for bt in system.bond_types:
        if len(bond_styles) > 1:
            if bt.style == "harmonic":
                f.write(
                    f"bond_coeff {bt.type_id} harmonic {bt.params[0]:.10g} {bt.params[1]:.10g}\n"
                )
            elif bt.style == "backmap/harmonic":
                f.write(
                    f"bond_coeff {bt.type_id} backmap/harmonic "
                    f"{bt.keyword} {bt.params[0]:.10g} {bt.params[1]:.10g}\n"
                )
            elif bt.style == "backmap/table":
                f.write(
                    f"bond_coeff {bt.type_id} backmap/table "
                    f"{bt.keyword} {bt.table_file} {bt.table_keyword}\n"
                )
        else:
            if bt.style == "harmonic":
                f.write(f"bond_coeff {bt.type_id} {bt.params[0]:.10g} {bt.params[1]:.10g}\n")
            elif bt.style == "backmap/harmonic":
                f.write(
                    f"bond_coeff {bt.type_id} {bt.keyword} {bt.params[0]:.10g} {bt.params[1]:.10g}\n"
                )
            elif bt.style == "backmap/table":
                f.write(
                    f"bond_coeff {bt.type_id} {bt.keyword} {bt.table_file} {bt.table_keyword}\n"
                )
    f.write("\n")

    # Angle style
    if system.angle_types:
        if len(angle_styles) > 1:
            f.write(f"angle_style hybrid {' '.join(angle_styles)}\n")
        elif angle_styles:
            f.write(f"angle_style {angle_styles[0]}\n")

        for angtype in system.angle_types:
            if len(angle_styles) > 1:
                if angtype.style == "harmonic":
                    f.write(
                        f"angle_coeff {angtype.type_id} harmonic "
                        f"{angtype.params[0]:.10g} {angtype.params[1]:.4f}\n"
                    )
                elif angtype.style == "backmap/harmonic":
                    f.write(
                        f"angle_coeff {angtype.type_id} backmap/harmonic "
                        f"{angtype.keyword} {angtype.params[0]:.10g} {angtype.params[1]:.4f}\n"
                    )
                elif angtype.style == "backmap/table":
                    f.write(
                        f"angle_coeff {angtype.type_id} backmap/table "
                        f"{angtype.keyword} {angtype.table_file} {angtype.table_keyword}\n"
                    )
                elif angtype.style == "backmap/charmm":
                    f.write(
                        f"angle_coeff {angtype.type_id} backmap/charmm {angtype.keyword} "
                        + " ".join(f"{p:.10g}" for p in angtype.params)
                        + "\n"
                    )
            else:
                if angtype.style == "harmonic":
                    f.write(
                        f"angle_coeff {angtype.type_id} "
                        f"{angtype.params[0]:.10g} {angtype.params[1]:.4f}\n"
                    )
                elif angtype.style == "backmap/harmonic":
                    f.write(
                        f"angle_coeff {angtype.type_id} "
                        f"{angtype.keyword} {angtype.params[0]:.10g} {angtype.params[1]:.4f}\n"
                    )
                elif angtype.style == "backmap/table":
                    f.write(
                        f"angle_coeff {angtype.type_id} "
                        f"{angtype.keyword} {angtype.table_file} {angtype.table_keyword}\n"
                    )
                elif angtype.style == "backmap/charmm":
                    f.write(
                        f"angle_coeff {angtype.type_id} {angtype.keyword} "
                        + " ".join(f"{p:.10g}" for p in angtype.params)
                        + "\n"
                    )
        f.write("\n")

    # Dihedral style
    if system.dihedral_types:
        if len(dihedral_styles) > 1:
            f.write(f"dihedral_style hybrid {' '.join(dihedral_styles)}\n")
        elif dihedral_styles:
            f.write(f"dihedral_style {dihedral_styles[0]}\n")

        for dihtype in system.dihedral_types:
            coeff = _format_dihedral_coeff(dihtype, dihedral_styles)
            f.write(coeff)
        f.write("\n")

    # Improper style (func-2 harmonic impropers only)
    if system.improper_types:
        f.write("improper_style backmap/harmonic\n")
        for imptype in system.improper_types:
            k_val, chi0 = imptype.params
            f.write(
                f"improper_coeff {imptype.type_id} {imptype.keyword} {k_val:.10g} {chi0:.10g}\n"
            )
        f.write("\n")

    # Special bonds (exclusions)
    nrexcl = sim.exclusion_nrexcl
    if sim.exclusion_nrexcl_cg is not None and sim.exclusion_nrexcl_cg != nrexcl:
        f.write(_special_bonds_split(nrexcl, sim.exclusion_nrexcl_cg))
    elif nrexcl >= 3:
        f.write("special_bonds lj 0.0 0.0 0.0 coul 0.0 0.0 0.0\n\n")
    elif nrexcl == 2:
        f.write("special_bonds lj 0.0 0.0 1.0 coul 0.0 0.0 1.0\n\n")
    elif nrexcl == 1:
        f.write("special_bonds lj 0.0 1.0 1.0 coul 0.0 1.0 1.0\n\n")

    # Groups
    at_type_str = " ".join(str(t) for t in params["at_type_ids"])
    cg_type_str = " ".join(str(t) for t in params["cg_type_ids"])
    f.write(f"group at_atoms type {at_type_str}\n")
    f.write(f"group cg_atoms type {cg_type_str}\n\n")
    f.write("neigh_modify delay 0 every 1 check yes\n\n")


def _write_backmap_fixes(
    f: IO[str],
    system: System,
    settings: Settings,
    params: dict[str, Any],
) -> None:
    """fix backmap and fix backmap/pairs, written to ``<prefix>.backmap.lmp``.

    Include it after the integrators: fix order decides whether the CG beads
    follow the AT atoms within the same step.
    """
    sim = settings.simulation
    # Fix backmap
    cg_type_fix_str = " ".join(str(t) for t in params["cg_type_ids"])
    fix_line = (
        f"fix bm all backmap cg_type {cg_type_fix_str} "
        f"alpha {sim.alpha} lambda0 {sim.initial_resolution}"
    )
    apb = params.get("apb_by_cg_type", {})
    if apb and len(set(apb.values())) > 1:
        apb_str = " ".join(f"{t}:{n}" for t, n in sorted(apb.items()))
        fix_line += f" apb {apb_str}"
    f.write(fix_line + "\n\n")

    if system.has_cross_pairs:
        f.write(f"fix pairs all backmap/pairs at file {system.cross_pairs_file}\n\n")


def _write_setup(
    f: IO[str],
    system: System,
    settings: Settings,
    params: dict[str, Any],
    data_filename: str,
    *,
    use_read_data: bool = True,
    ff_include: str | None = None,
    backmap_include: str | None = None,
) -> None:
    """Write the shared setup block (styles, coefficients, groups, fixes).

    With ``ff_include``/``backmap_include`` the force field and the backmap
    fixes are included from those files instead of written inline.
    """
    sim = settings.simulation

    if use_read_data:
        f.write(f"read_data {data_filename}\n\n")

    if ff_include:
        f.write(f"include {ff_include}\n\n")
    else:
        _write_forcefield(f, system, settings, params)

    _write_initial_velocities(f, sim, params)

    # Integration (AT atoms only) — must be defined BEFORE fix backmap so
    # that NVE/NVT initial_integrate runs first, updating AT positions before
    # fix backmap tracks the CG→COM.
    _write_integration(f, sim, params)

    if backmap_include:
        f.write(f"include {backmap_include}\n\n")
    else:
        _write_backmap_fixes(f, system, settings, params)

    if use_read_data and system.write_image_flags:
        # after the force field and fix backmap (pair_style backmap needs it)
        f.write("reset_atoms image all\n\n")

    _write_cap_force(f, sim)

    # Temperature compute on AT atoms only (CG atoms have zero velocity,
    # which would dilute the reported temperature).
    f.write("compute at_temp at_atoms temp\n\n")

    # First dynamics segment always uses the backmapping timestep. Using the
    # (often larger) production timestep during λ-frozen hybrid relaxation can
    # blow up before the ramp starts (missing bonded neighbors on dense melts).
    init_ts = params["ts_backmap_fs"]
    f.write(f"timestep {init_ts:.2f}\n\n")
    f.write(f"thermo {sim.energy_interval}\n")
    f.write("thermo_style custom step temp pe ke etotal press f_bm\n")
    f.write("thermo_modify colname f_bm lambda\n")
    f.write("thermo_modify temp at_temp\n\n")
    f.write(f"dump traj all custom {sim.trajectory_interval} dump.backmap id mol type x y z f_bm\n")
    f.write("dump_modify traj sort id\n\n")


def _write_restart_cmd(f: IO[str], restart_interval: int) -> None:
    """Write the LAMMPS restart command for alternating checkpoint files."""
    f.write(f"restart {restart_interval} restart.backmap restart.backmap2\n")


def write_cross_pairs_file(system: System, path: Path) -> None:
    """Write the explicit 1-4 pairs for fix backmap/pairs.

    Columns: atom IDs, LJ sigma (A), LJ epsilon (kcal/mol), 1-4 Coulomb scale.
    """
    with open(path, "w") as f:
        f.write(f"{len(system.cross_pairs)}\n")
        for pair in system.cross_pairs:
            f.write(
                f"{pair.i} {pair.j} {pair.sigma:.10g} {pair.epsilon:.10g} {pair.qq_scale:.10g}\n"
            )
    normalize_file_end(path)


def read_input_with_includes(path: Path) -> str:
    """Text of a LAMMPS input with ``include`` files expanded in place."""
    out: list[str] = []
    for line in path.read_text().splitlines():
        parts = line.split()
        if parts[:1] == ["include"] and len(parts) >= 2:
            out.append(read_input_with_includes(path.parent / parts[1]))
        else:
            out.append(line)
    return "\n".join(out) + "\n"


def write_forcefield_includes(
    system: System,
    settings: Settings,
    out_dir: Path,
    data_filename: str,
) -> tuple[str, str]:
    """Write ``<prefix>.ff.lmp`` and ``<prefix>.backmap.lmp``; return their names.

    Hand-written protocols include these instead of restating coefficients:
    ``include <prefix>.ff.lmp`` after read_data, the integrators, then
    ``include <prefix>.backmap.lmp``.
    """
    params = _compute_params(system, settings)
    prefix = Path(data_filename).stem
    ff_name = f"{prefix}.ff.lmp"
    backmap_name = f"{prefix}.backmap.lmp"
    with open(out_dir / ff_name, "w") as f:
        f.write(f"# Force field for {data_filename} -- generated by backmap-prep, do not edit\n\n")
        _write_forcefield(f, system, settings, params)
    with open(out_dir / backmap_name, "w") as f:
        f.write(
            "# fix backmap and 1-4 pairs -- generated by backmap-prep, do not edit.\n"
            "# Include after the integration fixes.\n\n"
        )
        _write_backmap_fixes(f, system, settings, params)
    normalize_file_end(out_dir / ff_name)
    normalize_file_end(out_dir / backmap_name)
    return ff_name, backmap_name


def _write_robust_protocol(
    f: IO[str],
    system: System,
    settings: Settings,
    params: dict[str, Any],
    data_filename: str,
    ff_name: str,
    backmap_name: str,
) -> None:
    """Robust multi-phase protocol for dense melts (``simulation.protocol: robust``).

    Phase 0: minimize and relax the AT overlaps at lambda = 0 with the CG beads
    frozen (nve/limit, Langevin, 0.01 fs). Phase 1: lambda ramp with nve/limit and
    Langevin at 0.1 fs for 2 / alpha steps. Phase 2: staged NVT at lambda = 1
    (0.25, 0.5, 1.0 fs). Optional production at lambda = 1.
    """
    sim = settings.simulation
    temp = sim.temperature
    seed = sim.rng_seed if sim.rng_seed > 0 else 48279
    ramp_steps = 2 * math.ceil(1.0 / sim.alpha)
    prefix = Path(data_filename).stem
    pairs = " f_pairs[1] f_pairs[2]" if system.has_cross_pairs else ""

    f.write(f"read_data {data_filename}\n\n")
    f.write(f"include {ff_name}\n\n")
    f.write(f"include {backmap_name}\n\n")
    if system.write_image_flags:
        # after the force field and fix backmap (pair_style backmap needs it)
        f.write("reset_atoms image all\n\n")
    _write_cap_force(f, sim)
    f.write("compute at_temp at_atoms temp\n")
    f.write(f"thermo {sim.energy_interval}\n")
    f.write(
        "thermo_style custom step temp pe ke etotal ebond eangle edihed evdwl ecoul"
        f"{pairs} press f_bm\n"
    )
    f.write("thermo_modify colname f_bm lambda temp at_temp\n\n")
    f.write(f"dump traj all custom {sim.trajectory_interval} dump.backmap id mol type x y z f_bm\n")
    f.write("dump_modify traj sort id\n\n")

    f.write("# Phase 0a: minimize AT overlaps at lambda = 0 (CG frozen)\n")
    f.write("fix freeze cg_atoms setforce 0.0 0.0 0.0\n")
    f.write("minimize 1.0e-4 1.0e-6 1000 10000\n\n")
    f.write("# Phase 0b: relax AT fragments at lambda = 0 (CG frozen)\n")
    f.write("fix relax at_atoms nve/limit 0.01\n")
    f.write(f"fix therm_relax at_atoms langevin {temp:.1f} {temp:.1f} 20.0 {seed + 1}\n")
    f.write("timestep 0.01\nrun 10000\n")
    f.write("unfix therm_relax\nunfix relax\nunfix freeze\n\n")
    f.write(f"# Phase 1: lambda ramp 0 -> 1 ({ramp_steps} steps at 0.1 fs, alpha {sim.alpha})\n")
    f.write("fix limit_all all nve/limit 0.05\n")
    f.write(f"fix therm_ramp at_atoms langevin {temp:.1f} {temp:.1f} 100.0 {seed + 2}\n")
    f.write("fix_modify bm active yes\n")
    f.write(f"timestep 0.10\nrun {ramp_steps}\n")
    f.write("unfix limit_all\nunfix therm_ramp\n\n")
    f.write("# Phase 2: NVT at lambda = 1, staged timestep\n")
    f.write(f"fix nvt_at at_atoms nvt temp {temp:.1f} {temp:.1f} 100.0\n")
    f.write(f"fix nvt_cg cg_atoms nvt temp {temp:.1f} {temp:.1f} 100.0\n")
    f.write("timestep 0.25\nrun 10000\ntimestep 0.50\nrun 5000\ntimestep 1.00\nrun 5000\n\n")
    f.write(f"write_data {prefix}_hybrid.data\n")
    if sim.production_steps > 0:
        f.write(f"\n# Production at lambda = 1\ntimestep {params['timestep_fs']:.2f}\n")
        f.write(f"run {sim.production_steps}\nwrite_data {prefix}_final.data\n")


def write_lammps_input(
    system: System,
    settings: Settings,
    path: Path,
    data_filename: str,
) -> None:
    """Write a LAMMPS input script for backmapping.

    When ``settings.simulation.restart_interval`` is set, also generates
    per-phase scripts and a shared setup include file.
    """
    _write_lammps_input(system, settings, path, data_filename)
    normalize_file_end(path)


def _write_lammps_input(
    system: System,
    settings: Settings,
    path: Path,
    data_filename: str,
) -> None:
    """Write a LAMMPS input script for backmapping.

    When ``settings.simulation.restart_interval`` is set, also generates
    per-phase scripts and a shared setup include file.
    """
    sim = settings.simulation
    params = _compute_params(system, settings)
    restart = sim.restart_interval
    ff_name, backmap_name = write_forcefield_includes(system, settings, path.parent, data_filename)

    with open(path, "w") as f:
        f.write("# LAMMPS input for backmapping — generated by backmap-prep\n")
        f.write("# Reference: Krajniak et al., JCTC 2016, DOI: 10.1021/acs.jctc.6b00595\n")
        f.write("#            Krajniak, Zhang et al., JCC 2018, DOI: 10.1002/jcc.25129\n\n")

        f.write("units real\n")
        f.write("atom_style full\n")
        f.write("boundary p p p\n\n")

        if sim.protocol == "robust":
            _write_robust_protocol(
                f, system, settings, params, data_filename, ff_name, backmap_name
            )
            return

        _write_setup(
            f,
            system,
            settings,
            params,
            data_filename,
            ff_include=ff_name,
            backmap_include=backmap_name,
        )

        if restart:
            _write_restart_cmd(f, restart)
            f.write("\n")

        if sim.equilibration_steps > 0:
            f.write(
                "# Phase 1: CG equilibration (λ frozen — optional if CG was pre-equilibrated)\n"
            )
            f.write("fix_modify bm active no\n")
            f.write(f"run {sim.equilibration_steps}\n")
            if restart:
                f.write("write_restart restart.backmap\n")
                f.write("shell echo done > phase_1.done\n")
            f.write("\n")

        # Backmapping: λ 0 → 1
        if sim.equilibration_steps > 0:
            f.write("# Phase 2: Backmapping\n")
            f.write(f"timestep {params['ts_backmap_fs']:.2f}\n")
        else:
            f.write("# Backmapping: λ 0 → 1\n")
        f.write("fix_modify bm active yes\n")
        f.write(f"run {params['backmapping_steps']}\n")
        if restart:
            f.write("write_restart restart.backmap\n")
            if sim.equilibration_steps > 0:
                f.write("shell echo done > phase_2.done\n")
            else:
                f.write("shell echo done > phase_1.done\n")
        f.write("\n")
        hybrid_out = data_filename.replace(".data", "_hybrid.data")
        f.write(f"write_data {hybrid_out}\n")

        if sim.production_steps > 0:
            if sim.equilibration_steps > 0:
                f.write("\n# Phase 3: AT production (optional post-backmap)\n")
            else:
                f.write("\n# AT production (λ = 1) in the same run\n")
            f.write(f"timestep {params['timestep_fs']:.2f}\n")
            f.write(f"run {sim.production_steps}\n")
            if restart:
                if sim.equilibration_steps > 0:
                    f.write("shell echo done > phase_3.done\n")
                else:
                    f.write("shell echo done > phase_2.done\n")
            final_out = data_filename.replace(".data", "_final.data")
            f.write(f"\nwrite_data {final_out}\n")

    # Generate per-phase scripts when restart is enabled
    if restart:
        _write_restart_scripts(system, settings, path, data_filename, params)


def _write_restart_scripts(
    system: System,
    settings: Settings,
    master_path: Path,
    data_filename: str,
    params: dict[str, Any],
) -> None:
    """Generate the setup include and per-phase restart scripts."""
    sim = settings.simulation
    restart = sim.restart_interval
    assert restart is not None

    parent = master_path.parent
    stem = master_path.name  # e.g. "in.backmap"
    phase3_path = parent / f"{stem}.phase3"

    # --- in.<prefix>.setup ---
    setup_path = parent / f"{stem}.setup"
    with open(setup_path, "w") as f:
        f.write("# Shared setup — generated by backmap-prep (do not edit)\n\n")
        _write_setup(
            f,
            system,
            settings,
            params,
            data_filename,
            use_read_data=False,
            ff_include=f"{Path(data_filename).stem}.ff.lmp",
            backmap_include=f"{Path(data_filename).stem}.backmap.lmp",
        )
        _write_restart_cmd(f, restart)
        f.write("\n")

    setup_name = setup_path.name
    hybrid_out = data_filename.replace(".data", "_hybrid.data")
    phase2_path = parent / f"{stem}.phase2"

    if sim.equilibration_steps == 0:
        if phase3_path.exists():
            phase3_path.unlink()

        # --- in.<prefix>.phase1 — backmapping only ---
        with open(parent / f"{stem}.phase1", "w") as f:
            f.write("# Phase 1: Backmapping λ 0→1 (restart-aware) — generated by backmap-prep\n\n")
            f.write("units real\n")
            f.write("atom_style full\n")
            f.write("boundary p p p\n\n")
            f.write(f"read_data {data_filename}\n\n")
            f.write(f"include {setup_name}\n\n")
            f.write("# Backmapping: λ 0 → 1\n")
            f.write(f"timestep {params['ts_backmap_fs']:.2f}\n")
            f.write("fix_modify bm active yes\n")
            f.write(f"run {params['backmapping_steps']}\n")
            f.write("write_restart restart.backmap\n")
            f.write(f"write_data {hybrid_out}\n")
            f.write("shell echo done > phase_1.done\n")

        if sim.production_steps > 0:
            with open(phase2_path, "w") as f:
                f.write("# Phase 2: AT production (restart-aware) — generated by backmap-prep\n\n")
                f.write("units real\n")
                f.write("atom_style full\n")
                f.write("boundary p p p\n\n")
                f.write("read_restart restart.backmap\n\n")
                f.write(f"include {setup_name}\n\n")
                f.write("# AT production (λ = 1)\n")
                f.write(f"timestep {params['timestep_fs']:.2f}\n")
                f.write(f"run {sim.production_steps}\n")
                f.write("shell echo done > phase_2.done\n")
        elif phase2_path.exists():
            phase2_path.unlink()
        return

    # --- in.<prefix>.phase1 — CG equilibration ---
    with open(parent / f"{stem}.phase1", "w") as f:
        f.write("# Phase 1: CG equilibration (restart-aware) — generated by backmap-prep\n\n")
        f.write("units real\n")
        f.write("atom_style full\n")
        f.write("boundary p p p\n\n")
        f.write(f"read_data {data_filename}\n\n")
        f.write(f"include {setup_name}\n\n")
        f.write("# Phase 1: CG equilibration\n")
        f.write("fix_modify bm active no\n")
        f.write(f"run {sim.equilibration_steps}\n")
        f.write("write_restart restart.backmap\n")
        f.write("shell echo done > phase_1.done\n")

    # --- in.<prefix>.phase2 — backmapping ---
    with open(parent / f"{stem}.phase2", "w") as f:
        f.write("# Phase 2: Backmapping (restart-aware) — generated by backmap-prep\n\n")
        f.write("units real\n")
        f.write("atom_style full\n")
        f.write("boundary p p p\n\n")
        f.write("read_restart restart.backmap\n\n")
        f.write(f"include {setup_name}\n\n")
        f.write("# Phase 2: Backmapping\n")
        f.write(f"timestep {params['ts_backmap_fs']:.2f}\n")
        f.write("fix_modify bm active yes\n")
        f.write(f"run {params['backmapping_steps']}\n")
        f.write("write_restart restart.backmap\n")
        f.write(f"write_data {hybrid_out}\n")
        f.write("shell echo done > phase_2.done\n")

    if sim.production_steps > 0:
        with open(phase3_path, "w") as f:
            f.write("# Phase 3: AT production (restart-aware) — generated by backmap-prep\n\n")
            f.write("units real\n")
            f.write("atom_style full\n")
            f.write("boundary p p p\n\n")
            f.write("read_restart restart.backmap\n\n")
            f.write(f"include {setup_name}\n\n")
            f.write("# Phase 3: AT production\n")
            f.write(f"timestep {params['timestep_fs']:.2f}\n")
            f.write(f"run {sim.production_steps}\n")
            f.write("shell echo done > phase_3.done\n")
    elif phase3_path.exists():
        phase3_path.unlink()
